services:
  cli:
    build: .
    privileged: true
    volumes:
      - ..:/workspaces/cli
      - ./fish:/root/.config/fish
      - /sys/kernel/tracing:/sys/kernel/tracing:ro
      - /sys/kernel/debug:/sys/kernel/debug:ro
